<a href="https://colab.research.google.com/github/ocelotzin/Tareas_analisis_numerico/blob/main/Tarea1/Ejercicio1/Ejercicio_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>Tarea 1 Analisis Numerico</i></h1>
  </font>
  <font color="Blue" face="Comic Sans MS,arial">
  <h5 align="center"><i>MARTINEZ ROSAS ZAYDE YAMILE</i></h5>
  <h5 align="center"><i>CAMACHO MARIN ANA KAREN</i></h5>
  <h5 align="center"><i>LÓPEZ AGUIRRE ROBERTO OCELOTZIN</i></h5>
  <h5 align="center"><i>VARGAS BAUTISTA EMMANUEL</i></h5>
  </font>

In [ ]:
#Librerias

import numpy as np
import matplotlib.pyplot as plt
import timeit
import time
import math
from scipy.linalg import fractional_matrix_power

##Ejercicio 1

#Ejercicio 1.1
 Programe la multiplicacion de matrices por bloques y compare tiempos de ejecucion contra el programa realizado en clase. Ojo, el nuevo programa debe ser mas rapido, escoja tamanos de 10 hasta 100.

In [ ]:
# Definir tamaño de la matriz
n = 100
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [ ]:
#MULTIPLICACION DE MATRICES EN CLASE

def MultMat(Mat1, Mat2):
    """
    Realiza la multiplicación de dos matrices.

    Parámetros:
    -----------
    Mat1 : numpy.ndarray
        Una matriz bidimensional de forma (n, m), donde 'n' es el número de filas
        y 'm' es el número de columnas.
    Mat2 : numpy.ndarray
        Una matriz bidimensional de forma (m, p), donde 'm' es el número de filas
        (debe coincidir con el número de columnas de Mat1) y 'p' es el número de
        columnas.

    Retorna:
    --------
    numpy.ndarray
        Una matriz bidimensional de forma (n, p) que representa el resultado de
        la multiplicación de Mat1 por Mat2.

    """
    # Inicializa una matriz de ceros con las dimensiones adecuadas
    Mat3 = np.zeros((Mat1.shape[0], Mat2.shape[1]))

    # Itera sobre cada fila de la primera matriz
    for row in range(Mat1.shape[0]):
        # Itera sobre cada columna de la segunda matriz
        for col in range(Mat2.shape[1]):
            # Realiza la multiplicación y suma los productos
            for aux in range(Mat2.shape[0]):
                Mat3[row, col] += Mat1[row, aux] * Mat2[aux, col]

    return Mat3


# Medir tiempo de ejecución
inicio = time.time()
C_CLASE = MultMat(A, B)  # Multiplicación clase
fin = time.time()

# Mostrar tiempo de ejecución
print(f"Tiempo de ejecución (multiplicación en clase): {fin - inicio:.6f} segundos")

# Mostrar una parte de la matriz resultado
print("Primeros 5 elementos de la primera fila (método en clase):", C_CLASE[0, :5])

Tiempo de ejecución (multiplicación en clase): 0.690885 segundos
Primeros 5 elementos de la primera fila (método en clase): [23.59306342 25.96653556 23.85119565 25.03562713 24.07887306]


In [ ]:
#MULTIPLICACION DE MATRICES POR BLOQUES

def multiplicacion_por_bloques(A, B, tam_bloque):
    """
    Multiplica dos matrices por bloques para mejorar eficiencia.

    Parámetros:
    -----------
    A : numpy.ndarray
        Matriz de tamaño (n, n)
    B : numpy.ndarray
        Matriz de tamaño (n, n)
    tam_bloque : int
        Tamaño del bloque para dividir la matriz.

    Retorna:
    --------
    numpy.ndarray
        Matriz resultante de la multiplicación de A y B por bloques.
    """
    n = A.shape[0]
    C = np.zeros((n, n))

    for i in range(0, n, tam_bloque):
        for j in range(0, n, tam_bloque):
            for k in range(0, n, tam_bloque):
                A_block = A[i:i+tam_bloque, k:k+tam_bloque]
                B_block = B[k:k+tam_bloque, j:j+tam_bloque]
                C[i:i+tam_bloque, j:j+tam_bloque] += MultMat(A_block, B_block)

    return C

# Definir tamaño del bloque
tam_bloque = 10

# Medir tiempo de ejecución
inicio = time.time()
C_bloques = multiplicacion_por_bloques(A, B, tam_bloque)
fin = time.time()

# Mostrar tiempo de ejecución
print(f"Tiempo de ejecución (multiplicación por bloques): {fin - inicio:.6f} segundos")

# Mostrar una parte de la matriz resultado
print("Primeros 5 elementos de la primera fila (método por bloques):", C_bloques[0, :5])

Tiempo de ejecución (multiplicación por bloques): 0.698200 segundos
Primeros 5 elementos de la primera fila (método por bloques): [24.82835684 24.71044741 26.42136856 25.79042537 24.87358555]


#Ejercicio 1.2
Programe la suma de matrices por bloques.

In [ ]:
#SUMA DE MATRICES POR BLOQUES

def suma_por_bloques(A, B, tam_bloque):
    """
    Realiza la suma de dos matrices por bloques

    Parámetros:
    -----------
    A : numpy.ndarray
        Matriz de tamaño (n, n)
    B : numpy.ndarray
        Matriz de tamaño (n, n)
    tam_bloque : int
        Tamaño del bloque para dividir la
        matriz.

    Retorna:
    --------
    numpy.ndarray
        Matriz resultante de la suma de A y B por bloques.
    """
    n = A.shape[0]
    C = np.zeros((n, n))

    for i in range(0, n, tam_bloque):
        for j in range(0, n, tam_bloque):
            # Extraer bloques de A y B
            A_block = A[i:i+tam_bloque, j:j+tam_bloque]
            B_block = B[i:i+tam_bloque, j:j+tam_bloque]

            # Sumar bloques y guardarlos en la matriz C
            C[i:i+tam_bloque, j:j+tam_bloque] = A_block + B_block

    return C

# Tamaño de la matriz
n = 100
tam_bloque = 10

# Crear matrices aleatorias
A = np.random.rand(n, n)
B = np.random.rand(n, n)

# Ejecutar la suma por bloques
C_bloques = suma_por_bloques(A, B, tam_bloque)

# Mostrar una parte del resultado
print("Suma por bloques:", C_bloques[0, :5])

Suma por bloques: [1.1200726  1.71901604 0.2189597  0.50006711 1.79544633]


#Ejercicio 1.3
Programa el producto punto de dos vectores en R^n, por bloques. Note que para que esto tenga relevancia computacional, la n debe ser mayor que 50.

In [ ]:
def producto_punto_bloques(v1, v2, tam_bloque):
    """
    Calcula el producto punto de dos vectores usando bloques.

    Parámetros:
    -----------
    v1, v2 : numpy.ndarray
        Vectores de tamaño n.
    tam_bloque : int
        Tamaño del bloque para dividir el cálculo.

    Retorna:
    --------
        Producto punto de los dos vectores.
    """
    n = len(v1)
    resultado = 0.0

    for i in range(0, n, tam_bloque):
        # Tomar una porción (bloque) de los vectores
        v1_bloque = v1[i:i+tam_bloque]
        v2_bloque = v2[i:i+tam_bloque]

        # Producto punto del bloque y sumarlo al resultado total
        resultado += (v1_bloque @ v2_bloque)

    return resultado

# Definir tamaño del bloque
tam_bloque = 10
v1 = np.random.rand(n)
v2 = np.random.rand(n)

# Medir tiempo de ejecución
inicio = time.time()
resultado_bloques = producto_punto_bloques(v1, v2, tam_bloque)
fin = time.time()

# Mostrar tiempo de ejecución y resultado
print(f"Resultado por bloques: {resultado_bloques:.6f}")

Resultado por bloques: 24.342543


#Ejercicio 1.4

Haga un programa que realice la transpuesta conjugada de una matriz compleja

In [ ]:
def conjugado_complejo(numero):
    """
    Calcula el conjugado de un número complejo.

    Parámetros:
    -----------
    numero :
      Número complejo del cual se calculará el conjugado. Debe ser de tipo 'complex'

    Retorna:
    --------
    Una tupla con dos elementos:
    - El primer elemento es la parte real del número complejo.
    - El segundo elemento es la parte imaginaria negada del número complejo.
    """
    return (numero.real, -numero.imag)

def transpuesta_conjugada(matriz):
    """
    Calcula la transpuesta conjugada de una matriz compleja.

    La transpuesta conjugada se obtiene al transponer la matriz (intercambiar filas por columnas) y calcular el conjugado complejo de cada elemento.
    Si la matriz es de dimensiones mxn, la transpuesta conjugada tendrá dimensiones nxm.

    Parámetros:
    -----------
    matriz : list of list of complex
        Matriz compleja de dimensiones mxn, representada como una lista de listas.
        Cada elemento de la matriz debe ser un número complejo (tipo 'complex').

    Retorna:
    --------
    list of list of complex
        Matriz transpuesta conjugada de dimensiones nxm, representada como una lista de listas.
        Cada elemento de la matriz resultante es el conjugado complejo del elemento correspondiente en la matriz original, pero en la posición transpuesta.
    """

    # Obtener las dimensiones de la matriz
    filas = len(matriz)
    columnas = len(matriz[0])

    # Crear una matriz vacía para almacenar el resultado con dimensiones invertidas respecto a la matriz original
    resultado = [[0j for _ in range(filas)] for _ in range(columnas)]

    # Calcular la transpuesta conjugada
    for i in range(filas):
        for j in range(columnas):
            # Obtener el conjugado del elemento (i, j)
            conjugado = conjugado_complejo(matriz[i][j])
            # Asignar el conjugado a la posición (j, i) en la matriz resultado
            resultado[j][i] = complex(conjugado[0], conjugado[1]) #convierte la tupla (real, imaginaria_negada) de nuevo a un número complejo.

    return resultado

# Ejemplo de uso
matriz_compleja = [
    [1 + 2j, 6 - 7j, 8j],
    [9 + 2j, 4-5j, 3 + 2j]
    ]

resultado = transpuesta_conjugada(matriz_compleja)
print("Transpuesta conjugada:")
for fila in resultado:
    print(fila)

Transpuesta conjugada:
[(1-2j), (9-2j)]
[(6+7j), (4+5j)]
[-8j, (3-2j)]


# Ejercicio 1.5
Haga un programa que realice la potencia de una matriz de tamaño 50×50. De preferencia utilice la multiplicación de matrices por bloques


In [ ]:
def potencia_matriz(A, p, tam_bloque):
    """
    Calcula A^p utilizando multiplicación por bloques.

    Parámetros:
    -----------
    A : Matriz cuadrada de tamaño n x n.
    p : Potencia a la que se elevará la matriz.
    tam_bloque : Tamaño del bloque para la multiplicación por bloques.

    Retorna:
    --------
        Matriz resultante de elevar A a la potencia p.
    """
    n = A.shape[0] # Obtiene el tamaño de la matriz (nxn)
    resultado = np.eye(n)  # Matriz identidad
    base = A.copy() # Copia la matriz A para usarla como base en las multiplicaciones

    """
    Descomponer la potencia p en potencias de 2: Esto se hace dividiendo p entre 2 repetidamente.
    Multiplicar la matriz base solo cuando p es impar.
    En cada iteración, la base se eleva al cuadrado para reducir el número de multiplicaciones.
    """
    while p > 0: # Itera mientras la potencia p sea mayor que 0
        if p % 2 == 1: # Si p es impar
            resultado = multiplicacion_por_bloques(resultado, base, tam_bloque) # Multiplica el resultado por la base
        base = multiplicacion_por_bloques(base, base, tam_bloque) # Eleva la base al cuadrado
        p //= 2 # Divide p entre 2 (división entera)

    return resultado

# Definir matriz 50x50 con números aleatorios del 1 al 10
A = np.random.randint(1, 51, (50, 50))

# Definir potencia a la que se elevará la matriz
p = 3

# Definir tamaño del bloque
tam_bloque = 5

# Mostrar una parte de la matriz original
print("Primeros 5x5 elementos de la matriz original:")
print(A[:5, :5])

# Mostrar una parte de la matriz resultado
A_potencia1 = potencia_matriz(A, p, tam_bloque)
print("Primeros 5x5 elementos de la matriz resultado:")
print(A_potencia1[:5, :5])




##########    Otra froma es utiliando las librerias SciPy o CuPy donde obtuvimos el mismo resultado   ###########
A_potencia2 = fractional_matrix_power(A, p)

# Mostrar la matriz original
print("Primeros 5x5 elementos de la matriz original:")
print(A[:5, :5])

# Mostrar una parte de la matriz resultado
print("Primeros 5x5 elementos de la matriz resultado:")
print(A_potencia2[:5, :5])

Primeros 5x5 elementos de la matriz original:
[[32 40 36  9 40]
 [30 29 31 10  1]
 [23 33 11 10 39]
 [15 31 36 29 30]
 [23  4 44 15 47]]
Primeros 5x5 elementos de la matriz resultado:
[[41157154. 44758271. 41480123. 45528802. 47668231.]
 [39449965. 42772729. 39801865. 43471170. 45477482.]
 [36806631. 39913114. 36675911. 40628341. 42413531.]
 [36874838. 40138736. 37561163. 40971927. 42735142.]
 [32173941. 34637137. 31907240. 35131164. 36881125.]]
Primeros 5x5 elementos de la matriz original:
[[32 40 36  9 40]
 [30 29 31 10  1]
 [23 33 11 10 39]
 [15 31 36 29 30]
 [23  4 44 15 47]]
Primeros 5x5 elementos de la matriz resultado:
[[41157154 44758271 41480123 45528802 47668231]
 [39449965 42772729 39801865 43471170 45477482]
 [36806631 39913114 36675911 40628341 42413531]
 [36874838 40138736 37561163 40971927 42735142]
 [32173941 34637137 31907240 35131164 36881125]]


# Ejercicio 1.6
Desarrollar un programa que calcule el producto cruz entre dos vectores tridimensionales.

Sean $a$ y $b$ dos vectores tridimencionales, es decir:
$$
a = (a_0, a_1, a_2) \ \ \ \text{y} \ \ \ b = (b_0, b_1, b_2)
$$

Entonces para calcular el producto creuz de ambos vectores realizamos lo siguiente

$$
\begin{align*}
a \times b &=
\begin{bmatrix}
i & j & k \\
a_0 & a_1 & a_2 \\
b_0 & b_1 & b_2
\end{bmatrix} \\
&= \ (a_1 b_2 - a_2 b_1)i - (a_0 b_2 - a_2 b_0)j + (a_0 b_1 - a_1 b_0)k \\
&= (a_1 b_2 - a_2 b_1)i + (a_2 b_0 - a_0 b_2 )j + (a_0 b_1 - a_1 b_0)k
\end{align*}
$$

Por lo que
$$
a \times b = ( \ (a_1 b_2 - a_2 b_1), (a_2 b_0 - a_0 b_2 ), (a_0 b_1 - a_1 b_0) \ )
$$

In [ ]:
def producto_cruz(a, b):
    """
    Calcula el producto cruz (o producto vectorial) entre dos vectores tridimensionales.

    Parámetros:
    -----------
    a : tuple or list
        Primer vector tridimensional, representado como una tupla o lista de tres elementos (x, y, z).
    b : tuple or list
        Segundo vector tridimensional, representado como una tupla o lista de tres elementos (x, y, z).

    Retorna:
    --------
    tuple
        Un vector tridimensional resultante del producto cruz, representado como una tupla (x, y, z).
    """
    componente_x = a[1] * b[2] - a[2] * b[1]
    componente_y = a[2] * b[0] - a[0] * b[2]
    componente_z = a[0] * b[1] - a[1] * b[0]

    return (componente_x, componente_y, componente_z)

# Ejemplo de uso
a = (8, 2, 7)
b = (2, 4, 6)

resultado = producto_cruz(a, b)
print("El producto cruz es:", resultado)




########## Para corroborar ocupamos la siguiente función de la librería NumPy, dandonos el mismo resultados ##########
print("Producto cruz utilizando np.cross:", np.cross(a, b))

El producto cruz es: (-16, -34, 28)
Producto cruz utilizando np.cross: [-16 -34  28]


#Ejercicio 1.7
Crear un programa que aplique una rotacion de un vector bidimensional
mediante una matriz de rotacion.

In [ ]:
def rotar_vector(v, theta):
    """
    Rotación a un vector bidimensional.

    Parámetros:
    -----------
    v : numpy.ndarray
        Vector original de tamaño (2,)
    theta : float
        Ángulo de rotación en radianes

    Retorna:
    --------
    numpy.ndarray
        Vector rotado
    """
    # Matriz de rotación
    R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

    return np.round((R @ v))

# Definir un vector original
v = np.array([1., 0.])

# Ángulo de rotación en radianes (90 grados = pi/2)
theta = np.pi / 2

# Aplicar rotación
v_rotado = rotar_vector(v, theta)

# Resultado
print(f"Vector original: {v}")
print(f"Vector rotado (90°): {v_rotado}")

Vector original: [1. 0.]
Vector rotado (90°): [0. 1.]


#Ejercicio 1.8

In [ ]:
def matriz_rotacion(eje, theta):
    """
    Matriz de rotación en 3D alrededor del eje dado.

    Parámetros:
    -----------
    eje : str
        Eje de rotación ("x", "y" o "z").
    theta : float
        Ángulo de rotación en radianes.

    Retorna:
    --------
    numpy.ndarray
        Matriz de rotación 3x3.
    """
    if eje == "x":
        R = np.array([[1, 0, 0], [0, np.cos(theta), -np.sin(theta)], [0, np.sin(theta), np.cos(theta)]])
    elif eje == "y":
        R = np.array([[np.cos(theta), 0, np.sin(theta)], [0, 1, 0],[-np.sin(theta), 0, np.cos(theta)]])
    elif eje == "z":
        R = np.array([[np.cos(theta), -np.sin(theta), 0],[np.sin(theta), np.cos(theta), 0],[0, 0, 1]])
    else:
        raise ValueError("El eje debe ser 'x', 'y' o 'z'")

    return R

def rotar_vector_3D(v, eje, theta):
    """
    Rotacion a un vector tridimensional usando una matriz de rotacin

    Parametros:
    -----------
    v : numpy.ndarray
        Vector original de tamaño (3,)
    eje : str
        Eje de rotacion ("x", "y" o "z")
    theta : float
        Angulo de rotacion en radianes

    Retorna:
    --------
    numpy.ndarray
        Vector rotado
    """
    # Obtener la matriz de rotacion correspondiente
    R = matriz_rotacion(eje, theta)

    # Multiplicamos la matriz de rotacion por el vector
    v_rotado = (R @ v)

    # Redondeamos para evitar errores numericos
    return np.round(v_rotado, 10)

# Definir un vector original en 3D
v = np.array([1., 0., 0.])

# Definir el eje de rotacion y el angulo (90° en radianes)
eje = "z"
theta = np.pi / 2

# Aplicar rotacion
v_rotado = rotar_vector_3D(v, eje, theta)

# Resultado
print(f"Vector original: {v}")
print(f"Vector rotado (90° alrededor de {eje}): {v_rotado}")

Vector original: [1. 0. 0.]
Vector rotado (90° alrededor de z): [0. 1. 0.]


#Ejercicio 1.9

Calcule la norma 1,

$$
\|A\|_1 = \max_{1 \leq j \leq n} \sum_{i=1}^{m} |a_{ij}|
$$

In [ ]:
def norma_1(matriz):
    """
    Calcula la norma 1 de una matriz.

    La norma 1 de una matriz se define como el máximo de las sumas de los valores absolutos
    de los elementos de cada columna.

    Parámetros:
    -----------
    matriz :
        Matriz de tamaño m x n, representada como una lista de listas.
        Cada elemento de la matriz debe ser un número (entero o flotante).

    Retorna:
    --------
    float
        La norma 1 de la matriz
    """
    sumas_columnas = []

    # Iteramos sobre cada columna
    for j in range(len(matriz[0])): #j recorre las columnas
        suma_columna = 0
        # Iteramos sobre cada fila para sumar los valores absolutos de la columna actual
        for i in range(len(matriz)): #i recorre las filas
            suma_columna += abs(matriz[i][j]) # Suma el valor absoluto del elemento (i, j)
        sumas_columnas.append(suma_columna)

    # máximo de las sumas de las columnas
    return max(sumas_columnas)

# Ejemplo de uso
matriz = [
    [1, -2, 3],
    [4, 5, -6],
    [7, 8, 9]
]

print("La norma 1 de la matriz es:", norma_1(matriz))





########## Para corroborar ocupamos la siguiente función de la librería NumPy, dandonos el mismo resultado ##########
norma_1 = np.linalg.norm(matriz, ord=1)
print("La norma 1 de la matriz utilizando numpy.linalg.norm es:", norma_1)

La norma 1 de la matriz es: 18
La norma 1 de la matriz utilizando numpy.linalg.norm es: 18.0


#Ejercicio 1.10
Calcule la norma infinito,

$$
\|A\|_{\infty} = \max_{1 \leq i \leq m} \sum_{j=1}^{n} |a_{ij}|
$$

In [ ]:

def norma_infinito_matriz(A):
    """
    Calcula la norma infinito de una matriz.

    Parámetros:
    -----------
    A : numpy.ndarray
        Matriz de tamaño (m, n)

    Retorna:
    --------
    float
        Norma infinito de la matriz.
    """
    return np.max(np.sum(np.abs(A), axis=1))  # Suma de filas y maximo

# Definir una matriz de ejemplo
A = np.array([[2, -3, 5],[1,  7, -6],[4, -2, 8]])

# Calcular la norma infinito
norma_inf_A = norma_infinito_matriz(A)

# Resultado
print(f"Matriz:\n{A}")
print(f"Norma infinito de A: {norma_inf_A}")

Matriz:
[[ 2 -3  5]
 [ 1  7 -6]
 [ 4 -2  8]]
Norma infinito de A: 14


#Ejercicio 1.11

Calcule la norma,

$$
\|A\|_2 = \sqrt{\sum_{j=1}^{m}\sum_{i=1}^{n} a_{ij}^2}
$$


In [ ]:
def norma_2(matriz):
    """
    Calcula la norma 2 de una matriz.

    Se define como la raíz cuadrada de la suma de los cuadrados de todos los elementos de la matriz.

    Parámetros:
    -----------
    matriz :
        Matriz de tamaño n x m, representada como una lista de listas.

    Retorna:
    --------
    float
        La norma 2 de la matriz.
    """

    suma_cuadrados = 0

    # Iteramos sobre cada fila y columna para sumar los cuadrados de los elementos
    for i in range(len(matriz)):  # Recorre las filas
      for j in range(len(matriz[i])):  # Recorre las columnas
        suma_cuadrados += matriz[i][j] ** 2 # Sumamos el cuadrado de cada elemento

    # La norma 2 es la raíz cuadrada de la suma de los cuadrados
    return math.sqrt(suma_cuadrados)

# Ejemplo de uso
matriz = [
    [1, -2, 3],
    [4, 5, -6],
    [7, 8, 9]
]
# Calculamos la norma 2 de la matriz
print("La norma 2 de la matriz es:", norma_2(matriz))

La norma 2 de la matriz es: 16.881943016134134
